title:  "MCG | Melina Carmona G"
tagline: "Melina Carmona Gómez"
description:
#author:
#  name: "Melina"
#  twitter: melinacarmonag

menu:
#- {name: 'Interesting Facts', file: 'facts.html'}
- {name: 'Fotografía', file: 'resources.html'}
- {name: 'Proyectos', file: 'sample-posts.html'}
- {name: 'Concursos', file: 'documentation.html'}
- {name: 'Sobre mí', file: 'sobremi.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/melinacarmonag'}
- {icon: 'facebook', link: 'https://www.facebook.com/melinacarmonag'}
- {icon: 'instagram', link: 'https://instagram.com/melinnacarmona'}
- {icon: 'envelope', link: 'mailto:arq.melinacarmonag@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
