title:  "MCG"
tagline: "Melina Carmona Gómez"
description:
#author:
#  name: "Melina"
#  twitter: melinacarmonag

menu:
- {name: 'Interesting Facts', file: 'facts.html'}
- {name: 'Learning Resources', file: 'resources.html'}
- {name: 'Sample Posts', file: 'sample-posts.html'}
- {name: 'Documentation', file: 'documentation.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contacto', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/melinacarmonag'}
- {icon: 'facebook', link: 'https://www.facebook.com/melinacarmonag'}
- {icon: 'instagram', link: 'https://instagram.com/melinnacarmona'}
# - {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope', link: 'mailto:arq.melinacarmonag@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
